### ISSUE TITLE
Error when evaluation metrics have the same value

### ISSUE THREAD

**Issue by gc-js** [wiesenfa/challengeR#31]
Dear @wiesenfa 
When I run multi-task challenges and all MetricValue values for a Task are the same, I get the following error:
`Error in seq.default(1.5, max(task$rank) - 0.5, by = 1) : 
  wrong sign in 'by' argument`

**Comment by wiesenfa** [comment]
thanks for pointing at it! Will take care of it asap.

**Comment by wiesenfa** [comment]
dear @gc-js
could you please provide a replicable example and code?

**Comment by wiesenfa** [comment]
dear @gc-js 
got it. Should be solved in develop branch

**Comment by gc-js** [comment]
Dear @wiesenfa
The code in the develop branch doesn't seem to solve my problem。
Here is my code and data:
![image](https://user-images.githubusercontent.com/55502012/115955798-66b13b80-a52b-11eb-8fd4-7dd805394120.png)
![image](https://user-images.githubusercontent.com/55502012/115955721-eb4f8a00-a52a-11eb-838d-24633ee12719.png)
![image](https://user-images.githubusercontent.com/55502012/115955847-c90a3c00-a52b-11eb-97e9-e5e4c60c7a7a.png)

**Comment by wiesenfa** [comment]
sorry, there is currently a deployment issue, I'll let you know when uploaded @gc-js

**Comment by wiesenfa** [comment]
dear  @gc-js , sorry for the delay, updated develop now online. Please let me know if you still encounter problems and thanks again at pointing at this one!

**Comment by gc-js** [comment]
It works! thank you!
